name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ricardoandreh/aval-pratica-app
  K8S_REPO: ricardoandreh/aval-pratica-k8s
  K8S_REPO_BRANCH: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest src/test_main.py

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.K8S_REPO_DEPLOY_KEY }}

      - name: Checkout Kubernetes repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.K8S_REPO }}
          path: k8s-repo
          ref: ${{ env.K8S_REPO_BRANCH }}
          ssh-key: ${{ secrets.K8S_REPO_DEPLOY_KEY }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization.yaml
        working-directory: k8s-repo
        run: |
          kustomize edit set image app=${{ env.IMAGE_NAME }}:${{ github.sha }}
          git diff

      - name: Commit and push changes to K8s repository
        working-directory: k8s-repo
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

          if git diff --quiet; then
            echo "Nenhuma mudança detectada no repositório K8s"
            exit 0
          fi

          git commit -am "deploy: update image to ${{ github.sha }}

          - Repository: ${{ github.repository }}
          - Commit: ${{ github.sha }}
          - Author: ${{ github.actor }}
          - Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          - Image: ${{ env.IMAGE_NAME }}:${{ github.sha }}"

          git push origin ${{ env.K8S_REPO_BRANCH }}

      - name: Create deployment summary
        if: always()
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: \`${{ env.IMAGE_NAME }}:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **K8s Repository**"
